# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: obj.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='obj.proto',
  package='grpcstream',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tobj.proto\x12\ngrpcstream\"\x8b\x01\n\x0fObjectExtraInfo\x12\x0e\n\x06length\x18\x01 \x01(\x02\x12\r\n\x05width\x18\x02 \x01(\x02\x12\x0e\n\x06height\x18\x03 \x01(\x02\x12\r\n\x05\x63olor\x18\x04 \x01(\x05\x12\x14\n\x0clicensePlate\x18\x05 \x01(\t\x12\x14\n\x0cvehicleBrand\x18\x06 \x01(\x05\x12\x0e\n\x06status\x18\x07 \x03(\x05\"\xc8\x01\n\x06Object\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06source\x18\x02 \x01(\x05\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\x0b\n\x03lat\x18\x04 \x01(\x01\x12\x0b\n\x03lng\x18\x05 \x01(\x01\x12\x0b\n\x03\x65le\x18\x06 \x01(\x01\x12\x0e\n\x06roadId\x18\x07 \x01(\t\x12\r\n\x05speed\x18\x08 \x01(\x02\x12\x0f\n\x07heading\x18\t \x01(\x02\x12\r\n\x05lanes\x18\n \x03(\x05\x12.\n\textraInfo\x18\x0b \x01(\x0b\x32\x1b.grpcstream.ObjectExtraInfo\"`\n\x11PubobjRequestData\x12\x10\n\x08\x64\x65viceNo\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x12\x12&\n\nobjectList\x18\x03 \x03(\x0b\x32\x12.grpcstream.Object\")\n\x0cResponseData\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t2T\n\rStreamService\x12\x43\n\x06Pubobj\x12\x1d.grpcstream.PubobjRequestData\x1a\x18.grpcstream.ResponseData\"\x00\x62\x06proto3')
)




_OBJECTEXTRAINFO = _descriptor.Descriptor(
  name='ObjectExtraInfo',
  full_name='grpcstream.ObjectExtraInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='grpcstream.ObjectExtraInfo.length', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='grpcstream.ObjectExtraInfo.width', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='grpcstream.ObjectExtraInfo.height', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='grpcstream.ObjectExtraInfo.color', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='licensePlate', full_name='grpcstream.ObjectExtraInfo.licensePlate', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vehicleBrand', full_name='grpcstream.ObjectExtraInfo.vehicleBrand', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='grpcstream.ObjectExtraInfo.status', index=6,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=165,
)


_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='grpcstream.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grpcstream.Object.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='grpcstream.Object.source', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='grpcstream.Object.type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat', full_name='grpcstream.Object.lat', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lng', full_name='grpcstream.Object.lng', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ele', full_name='grpcstream.Object.ele', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roadId', full_name='grpcstream.Object.roadId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='grpcstream.Object.speed', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading', full_name='grpcstream.Object.heading', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lanes', full_name='grpcstream.Object.lanes', index=9,
      number=10, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extraInfo', full_name='grpcstream.Object.extraInfo', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=368,
)


_PUBOBJREQUESTDATA = _descriptor.Descriptor(
  name='PubobjRequestData',
  full_name='grpcstream.PubobjRequestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceNo', full_name='grpcstream.PubobjRequestData.deviceNo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='grpcstream.PubobjRequestData.timestamp', index=1,
      number=2, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='objectList', full_name='grpcstream.PubobjRequestData.objectList', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=466,
)


_RESPONSEDATA = _descriptor.Descriptor(
  name='ResponseData',
  full_name='grpcstream.ResponseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='grpcstream.ResponseData.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='grpcstream.ResponseData.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=509,
)

_OBJECT.fields_by_name['extraInfo'].message_type = _OBJECTEXTRAINFO
_PUBOBJREQUESTDATA.fields_by_name['objectList'].message_type = _OBJECT
DESCRIPTOR.message_types_by_name['ObjectExtraInfo'] = _OBJECTEXTRAINFO
DESCRIPTOR.message_types_by_name['Object'] = _OBJECT
DESCRIPTOR.message_types_by_name['PubobjRequestData'] = _PUBOBJREQUESTDATA
DESCRIPTOR.message_types_by_name['ResponseData'] = _RESPONSEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObjectExtraInfo = _reflection.GeneratedProtocolMessageType('ObjectExtraInfo', (_message.Message,), dict(
  DESCRIPTOR = _OBJECTEXTRAINFO,
  __module__ = 'obj_pb2'
  # @@protoc_insertion_point(class_scope:grpcstream.ObjectExtraInfo)
  ))
_sym_db.RegisterMessage(ObjectExtraInfo)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), dict(
  DESCRIPTOR = _OBJECT,
  __module__ = 'obj_pb2'
  # @@protoc_insertion_point(class_scope:grpcstream.Object)
  ))
_sym_db.RegisterMessage(Object)

PubobjRequestData = _reflection.GeneratedProtocolMessageType('PubobjRequestData', (_message.Message,), dict(
  DESCRIPTOR = _PUBOBJREQUESTDATA,
  __module__ = 'obj_pb2'
  # @@protoc_insertion_point(class_scope:grpcstream.PubobjRequestData)
  ))
_sym_db.RegisterMessage(PubobjRequestData)

ResponseData = _reflection.GeneratedProtocolMessageType('ResponseData', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEDATA,
  __module__ = 'obj_pb2'
  # @@protoc_insertion_point(class_scope:grpcstream.ResponseData)
  ))
_sym_db.RegisterMessage(ResponseData)



_STREAMSERVICE = _descriptor.ServiceDescriptor(
  name='StreamService',
  full_name='grpcstream.StreamService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=511,
  serialized_end=595,
  methods=[
  _descriptor.MethodDescriptor(
    name='Pubobj',
    full_name='grpcstream.StreamService.Pubobj',
    index=0,
    containing_service=None,
    input_type=_PUBOBJREQUESTDATA,
    output_type=_RESPONSEDATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STREAMSERVICE)

DESCRIPTOR.services_by_name['StreamService'] = _STREAMSERVICE

# @@protoc_insertion_point(module_scope)
